# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_app', '0005_auto_20170425_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='trips_attending', to='first_app.User')),
            ],
        ),
    ]
