# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20170425_1755'),
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_trips', to='first_app.User'),
            preserve_default=False,
        ),
    ]
